# -*- mode: ruby -*-
# vi: set ft=ruby :

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require 'vagrant-shell-local'

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision :shell_local, command: ['bash', '-c', 'touch /tmp/hostshell-works && echo hello from the host && hostname 1>&2']
end
